
name: Java CI/CD with Gradle

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  # permissions:
  # contents: read

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.TOKEN}}
      
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setting Permissions
        run: chmod a+x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - name: Test with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: test
      - name: Run Test Coverage
        run: ./gradlew jacocoTestReport
      - name: Jacoco
        uses: cicirello/jacoco-badge-generator@v2.9.0
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          generate-summary: true
          summary-filename: "coverage-summary.json"
          fail-on-branches-decrease: true
          fail-on-coverage-decrease: true
      - name: Save Jacoco Summary
        run: |
          if [[ $(git status .github/badges --porcelain) ]]; then
            git config --global user.name 'ZheyueZhao'
            git config --global user.email 'zheyuezhao@gmail.com'
            git add '.github/badges'
            git commit -m "Autogenerated JaCoCo report"
            git push
          fi

  build_and_publish_docker_image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [build_and_test]

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Container image
        run: docker build -t ${{ secrets.DOCKER_REPO }}:latest .
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}
